[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[build]
  command = "npm run build"
  publish = ".next"

  # ✅ Cache the Next.js build output for faster builds
  [build.cache]
    paths = [
      ".next/cache"
    ]
