services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      # Persist workflows, credentials, etc.
      - n8n_data:/home/node/.n8n
      # Mount the Aiven CA cert into the container
      - ./pki:/opt/aiven-ca.pem:ro

volumes:
  n8n_data:
