services:
  django-search-api:
    container_name: django-search-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./pki:/opt/aiven-ca.pem:ro
    networks:
      - app-network
    depends_on:
      - redis-cache

  redis-cache:
    container_name: redis-cache
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    name: ai-bot-network
    external: true
