# Generated by Django 5.2 on 2025-04-15 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('success_rate', models.FloatField(default=100.0)),
            ],
            options={
                'verbose_name_plural': 'Proxies',
                'db_table': 'search_proxies',
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('engine', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Search Queries',
                'db_table': 'search_queries',
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scrapper.searchquery')),
            ],
            options={
                'verbose_name_plural': 'Search Results',
                'db_table': 'search_results',
            },
        ),
    ]
