# Generated by Django 5.2 on 2025-04-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proxy',
            unique_together={('ip', 'port')},
        ),
        migrations.AddField(
            model_name='proxy',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='ip',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='protocol',
            field=models.CharField(default='http', max_length=10),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='proxy',
            table='proxies',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='last_used',
        ),
    ]
